export interface Casino {
  name: string;
  city: string;
}

export interface CasinosByState {
  [state: string]: Casino[];
}

export const CASINOS_BY_STATE: CasinosByState = {
  'Nevada': [
    { name: 'Bellagio', city: 'Las Vegas' },
    { name: 'MGM Grand', city: 'Las Vegas' },
    { name: 'Caesars Palace', city: 'Las Vegas' },
    { name: 'The Venetian', city: 'Las Vegas' },
    { name: 'Wynn Las Vegas', city: 'Las Vegas' },
    { name: 'Aria Resort & Casino', city: 'Las Vegas' },
    { name: 'Cosmopolitan', city: 'Las Vegas' },
    { name: 'Mandalay Bay', city: 'Las Vegas' },
    { name: 'Luxor', city: 'Las Vegas' },
    { name: 'Paris Las Vegas', city: 'Las Vegas' },
    { name: 'Planet Hollywood', city: 'Las Vegas' },
    { name: 'Treasure Island', city: 'Las Vegas' },
    { name: 'Mirage', city: 'Las Vegas' },
    { name: 'Flamingo', city: 'Las Vegas' },
    { name: 'Harrah\'s Las Vegas', city: 'Las Vegas' },
    { name: 'Golden Nugget', city: 'Las Vegas' },
    { name: 'Red Rock Casino', city: 'Las Vegas' },
    { name: 'Station Casinos - Palace Station', city: 'Las Vegas' },
    { name: 'Station Casinos - Boulder Station', city: 'Las Vegas' },
    { name: 'Station Casinos - Sunset Station', city: 'Las Vegas' },
    { name: 'Atlantis Casino Resort Spa', city: 'Reno' },
    { name: 'Peppermill Resort Spa Casino', city: 'Reno' },
    { name: 'Grand Sierra Resort', city: 'Reno' },
    { name: 'Circus Circus Reno', city: 'Reno' },
    { name: 'Eldorado Resort Casino', city: 'Reno' },
  ],
  'New Jersey': [
    { name: 'Borgata Hotel Casino & Spa', city: 'Atlantic City' },
    { name: 'Hard Rock Hotel & Casino Atlantic City', city: 'Atlantic City' },
    { name: 'Ocean Casino Resort', city: 'Atlantic City' },
    { name: 'Tropicana Atlantic City', city: 'Atlantic City' },
    { name: 'Caesars Atlantic City', city: 'Atlantic City' },
    { name: 'Harrah\'s Resort Atlantic City', city: 'Atlantic City' },
    { name: 'Resorts Casino Hotel', city: 'Atlantic City' },
    { name: 'Golden Nugget Atlantic City', city: 'Atlantic City' },
    { name: 'Bally\'s Atlantic City', city: 'Atlantic City' },
  ],
  'California': [
    { name: 'Pechanga Resort Casino', city: 'Temecula' },
    { name: 'San Manuel Casino', city: 'Highland' },
    { name: 'Morongo Casino Resort & Spa', city: 'Cabazon' },
    { name: 'Viejas Casino & Resort', city: 'Alpine' },
    { name: 'Pala Casino Spa Resort', city: 'Pala' },
    { name: 'Chumash Casino Resort', city: 'Santa Ynez' },
    { name: 'Thunder Valley Casino Resort', city: 'Lincoln' },
    { name: 'Cache Creek Casino Resort', city: 'Brooks' },
    { name: 'Graton Resort & Casino', city: 'Rohnert Park' },
    { name: 'Agua Caliente Casino Resort Spa', city: 'Rancho Mirage' },
    { name: 'Fantasy Springs Resort Casino', city: 'Indio' },
    { name: 'Barona Resort & Casino', city: 'Lakeside' },
    { name: 'Sycuan Casino Resort', city: 'El Cajon' },
    { name: 'San Diego Casino', city: 'San Diego' },
  ],
  'Pennsylvania': [
    { name: 'Parx Casino', city: 'Bensalem' },
    { name: 'Rivers Casino Philadelphia', city: 'Philadelphia' },
    { name: 'Live! Casino & Hotel Philadelphia', city: 'Philadelphia' },
    { name: 'Rivers Casino Pittsburgh', city: 'Pittsburgh' },
    { name: 'The Meadows Racetrack and Casino', city: 'Washington' },
    { name: 'Mount Airy Casino Resort', city: 'Mount Pocono' },
    { name: 'Mohegan Sun Pocono', city: 'Wilkes-Barre' },
    { name: 'Wind Creek Bethlehem', city: 'Bethlehem' },
    { name: 'Hollywood Casino at Penn National Race Course', city: 'Grantville' },
    { name: 'Harrah\'s Philadelphia Casino & Racetrack', city: 'Chester' },
  ],
  'Connecticut': [
    { name: 'Foxwoods Resort Casino', city: 'Mashantucket' },
    { name: 'Mohegan Sun', city: 'Uncasville' },
  ],
  'Louisiana': [
    { name: 'L\'Auberge Casino Resort Lake Charles', city: 'Lake Charles' },
    { name: 'Golden Nugget Lake Charles', city: 'Lake Charles' },
    { name: 'Coushatta Casino Resort', city: 'Kinder' },
    { name: 'Paragon Casino Resort', city: 'Marksville' },
    { name: 'Harrah\'s New Orleans', city: 'New Orleans' },
    { name: 'Boomtown Casino New Orleans', city: 'New Orleans' },
    { name: 'Treasure Chest Casino', city: 'Kenner' },
    { name: 'Horseshoe Bossier City', city: 'Bossier City' },
    { name: 'Margaritaville Resort Casino', city: 'Bossier City' },
  ],
  'Mississippi': [
    { name: 'Beau Rivage Resort & Casino', city: 'Biloxi' },
    { name: 'Hard Rock Hotel & Casino Biloxi', city: 'Biloxi' },
    { name: 'IP Casino Resort Spa', city: 'Biloxi' },
    { name: 'Golden Nugget Biloxi', city: 'Biloxi' },
    { name: 'Palace Casino Resort', city: 'Biloxi' },
    { name: 'Treasure Bay Casino and Hotel', city: 'Biloxi' },
    { name: 'Scarlet Pearl Casino Resort', city: 'D\'Iberville' },
    { name: 'Horseshoe Tunica', city: 'Tunica' },
    { name: 'Gold Strike Casino Resort', city: 'Tunica' },
    { name: 'Sam\'s Town Hotel & Gambling Hall', city: 'Tunica' },
  ],
  'Michigan': [
    { name: 'MGM Grand Detroit', city: 'Detroit' },
    { name: 'MotorCity Casino Hotel', city: 'Detroit' },
    { name: 'Greektown Casino-Hotel', city: 'Detroit' },
    { name: 'FireKeepers Casino Hotel', city: 'Battle Creek' },
    { name: 'Four Winds Casino Resort', city: 'New Buffalo' },
    { name: 'Soaring Eagle Casino & Resort', city: 'Mount Pleasant' },
    { name: 'Gun Lake Casino', city: 'Wayland' },
  ],
  'Indiana': [
    { name: 'Horseshoe Hammond', city: 'Hammond' },
    { name: 'Hard Rock Casino Northern Indiana', city: 'Gary' },
    { name: 'Blue Chip Casino Hotel Spa', city: 'Michigan City' },
    { name: 'Horseshoe Indianapolis', city: 'Indianapolis' },
    { name: 'Hollywood Casino Lawrenceburg', city: 'Lawrenceburg' },
    { name: 'Belterra Casino Resort', city: 'Florence' },
    { name: 'French Lick Resort Casino', city: 'French Lick' },
  ],
  'Illinois': [
    { name: 'Rivers Casino Des Plaines', city: 'Des Plaines' },
    { name: 'Hollywood Casino Aurora', city: 'Aurora' },
    { name: 'Grand Victoria Casino', city: 'Elgin' },
    { name: 'Harrah\'s Joliet Casino', city: 'Joliet' },
    { name: 'Hollywood Casino Joliet', city: 'Joliet' },
    { name: 'Par-A-Dice Hotel Casino', city: 'East Peoria' },
  ],
  'Missouri': [
    { name: 'Ameristar Casino Hotel Kansas City', city: 'Kansas City' },
    { name: 'Harrah\'s North Kansas City', city: 'Kansas City' },
    { name: 'Hollywood Casino St. Louis', city: 'Maryland Heights' },
    { name: 'River City Casino & Hotel', city: 'St. Louis' },
    { name: 'Lumiere Place Casino', city: 'St. Louis' },
    { name: 'Ameristar Casino Resort Spa St. Charles', city: 'St. Charles' },
  ],
  'Oklahoma': [
    { name: 'WinStar World Casino and Resort', city: 'Thackerville' },
    { name: 'Choctaw Casino Resort', city: 'Durant' },
    { name: 'River Spirit Casino Resort', city: 'Tulsa' },
    { name: 'Hard Rock Hotel & Casino Tulsa', city: 'Catoosa' },
    { name: 'Cherokee Casino & Hotel West Siloam Springs', city: 'West Siloam Springs' },
    { name: 'Downstream Casino Resort', city: 'Quapaw' },
  ],
  'Florida': [
    { name: 'Seminole Hard Rock Hotel & Casino Tampa', city: 'Tampa' },
    { name: 'Seminole Hard Rock Hotel & Casino Hollywood', city: 'Hollywood' },
    { name: 'Seminole Casino Coconut Creek', city: 'Coconut Creek' },
    { name: 'Seminole Casino Brighton', city: 'Okeechobee' },
    { name: 'Seminole Casino Immokalee', city: 'Immokalee' },
    { name: 'Miccosukee Resort & Gaming', city: 'Miami' },
    { name: 'Magic City Casino', city: 'Miami' },
    { name: 'Hialeah Park Casino', city: 'Hialeah' },
  ],
  'New York': [
    { name: 'Resorts World Casino New York City', city: 'Queens' },
    { name: 'Empire City Casino', city: 'Yonkers' },
    { name: 'Turning Stone Resort Casino', city: 'Verona' },
    { name: 'del Lago Resort & Casino', city: 'Waterloo' },
    { name: 'Tioga Downs Casino Resort', city: 'Nichols' },
    { name: 'Rivers Casino & Resort Schenectady', city: 'Schenectady' },
    { name: 'Akwesasne Mohawk Casino Resort', city: 'Hogansburg' },
  ],
  'Maryland': [
    { name: 'MGM National Harbor', city: 'Oxon Hill' },
    { name: 'Live! Casino & Hotel Maryland', city: 'Hanover' },
    { name: 'Horseshoe Casino Baltimore', city: 'Baltimore' },
    { name: 'Hollywood Casino Perryville', city: 'Perryville' },
    { name: 'Ocean Downs Casino', city: 'Berlin' },
    { name: 'Rocky Gap Casino Resort', city: 'Flintstone' },
  ],
  'Massachusetts': [
    { name: 'Encore Boston Harbor', city: 'Everett' },
    { name: 'MGM Springfield', city: 'Springfield' },
    { name: 'Plainridge Park Casino', city: 'Plainville' },
  ],
  'Iowa': [
    { name: 'Prairie Meadows Casino', city: 'Altoona' },
    { name: 'Horseshoe Council Bluffs', city: 'Council Bluffs' },
    { name: 'Ameristar Casino Hotel Council Bluffs', city: 'Council Bluffs' },
    { name: 'Diamond Jo Casino', city: 'Dubuque' },
    { name: 'Riverside Casino & Golf Resort', city: 'Riverside' },
  ],
  'Colorado': [
    { name: 'Ameristar Casino Resort Spa Black Hawk', city: 'Black Hawk' },
    { name: 'Golden Gates Casino', city: 'Black Hawk' },
    { name: 'The Lodge Casino', city: 'Black Hawk' },
    { name: 'Monarch Casino Black Hawk', city: 'Black Hawk' },
    { name: 'Sky Ute Casino Resort', city: 'Ignacio' },
  ],
  'Arizona': [
    { name: 'Talking Stick Resort', city: 'Scottsdale' },
    { name: 'Casino Arizona', city: 'Scottsdale' },
    { name: 'Desert Diamond Casino West Valley', city: 'Glendale' },
    { name: 'Harrah\'s Ak-Chin Casino', city: 'Maricopa' },
    { name: 'Wild Horse Pass Hotel & Casino', city: 'Chandler' },
    { name: 'Fort McDowell Casino', city: 'Fountain Hills' },
  ],
  'Washington': [
    { name: 'Tulalip Resort Casino', city: 'Tulalip' },
    { name: 'Snoqualmie Casino', city: 'Snoqualmie' },
    { name: 'Muckleshoot Casino', city: 'Auburn' },
    { name: 'Emerald Queen Casino', city: 'Tacoma' },
    { name: 'Ilani Casino Resort', city: 'Ridgefield' },
    { name: 'Northern Quest Resort & Casino', city: 'Airway Heights' },
  ],
  'Oregon': [
    { name: 'Chinook Winds Casino Resort', city: 'Lincoln City' },
    { name: 'Spirit Mountain Casino', city: 'Grand Ronde' },
    { name: 'Wildhorse Resort & Casino', city: 'Pendleton' },
    { name: 'The Mill Casino Hotel & RV Park', city: 'North Bend' },
  ],
  'Minnesota': [
    { name: 'Mystic Lake Casino Hotel', city: 'Prior Lake' },
    { name: 'Treasure Island Resort & Casino', city: 'Welch' },
    { name: 'Grand Casino Mille Lacs', city: 'Onamia' },
    { name: 'Grand Casino Hinckley', city: 'Hinckley' },
    { name: 'Black Bear Casino Resort', city: 'Carlton' },
  ],
  'Wisconsin': [
    { name: 'Potawatomi Hotel & Casino', city: 'Milwaukee' },
    { name: 'Ho-Chunk Gaming Wisconsin Dells', city: 'Baraboo' },
    { name: 'Oneida Casino', city: 'Green Bay' },
    { name: 'Menominee Casino Resort', city: 'Keshena' },
  ],
  'Kansas': [
    { name: 'Kansas Star Casino', city: 'Mulvane' },
    { name: 'Hollywood Casino at Kansas Speedway', city: 'Kansas City' },
    { name: 'Boot Hill Casino & Resort', city: 'Dodge City' },
    { name: 'Casino White Cloud', city: 'White Cloud' },
  ],
  'West Virginia': [
    { name: 'Hollywood Casino at Charles Town Races', city: 'Charles Town' },
    { name: 'Mountaineer Casino Racetrack and Resort', city: 'Chester' },
    { name: 'Wheeling Island Hotel-Casino-Racetrack', city: 'Wheeling' },
    { name: 'Mardi Gras Casino & Resort', city: 'Nitro' },
  ],
  'Rhode Island': [
    { name: 'Twin River Casino Hotel', city: 'Lincoln' },
    { name: 'Tiverton Casino Hotel', city: 'Tiverton' },
  ],
  'Delaware': [
    { name: 'Dover Downs Hotel & Casino', city: 'Dover' },
    { name: 'Harrington Raceway & Casino', city: 'Harrington' },
    { name: 'Delaware Park Casino', city: 'Wilmington' },
  ],
  'New Mexico': [
    { name: 'Sandia Resort & Casino', city: 'Albuquerque' },
    { name: 'Isleta Resort & Casino', city: 'Albuquerque' },
    { name: 'Santa Ana Star Casino Hotel', city: 'Bernalillo' },
    { name: 'Buffalo Thunder Resort & Casino', city: 'Santa Fe' },
    { name: 'Inn of the Mountain Gods Resort & Casino', city: 'Mescalero' },
  ],
  'South Dakota': [
    { name: 'Deadwood Mountain Grand', city: 'Deadwood' },
    { name: 'Cadillac Jack\'s Gaming Resort', city: 'Deadwood' },
    { name: 'Silverado Franklin Hotel & Gaming Complex', city: 'Deadwood' },
    { name: 'Royal River Casino & Hotel', city: 'Flandreau' },
  ],
  'North Dakota': [
    { name: 'Spirit Lake Casino & Resort', city: 'Spirit Lake' },
    { name: 'Four Bears Casino & Lodge', city: 'New Town' },
    { name: 'Sky Dancer Casino & Resort', city: 'Belcourt' },
  ],
  'Montana': [
    { name: 'Northern Winz Casino', city: 'Billings' },
    { name: 'Charging Horse Casino', city: 'Lame Deer' },
    { name: 'Little Big Horn Casino', city: 'Crow Agency' },
  ],
  'Wyoming': [
    { name: 'Wind River Hotel and Casino', city: 'Riverton' },
    { name: '789 Smoke Shop & Casino', city: 'Riverton' },
  ],
  'Idaho': [
    { name: 'Coeur d\'Alene Casino Resort Hotel', city: 'Worley' },
    { name: 'Clearwater River Casino', city: 'Lewiston' },
    { name: 'It\'se-Ye-Ye Casino', city: 'Kamiah' },
  ],
  'Alabama': [
    { name: 'Wind Creek Casino & Hotel Atmore', city: 'Atmore' },
    { name: 'Wind Creek Casino & Hotel Montgomery', city: 'Montgomery' },
    { name: 'Wind Creek Casino & Hotel Wetumpka', city: 'Wetumpka' },
  ],
  'North Carolina': [
    { name: 'Harrah\'s Cherokee Casino Resort', city: 'Cherokee' },
    { name: 'Harrah\'s Cherokee Valley River', city: 'Murphy' },
  ],
  'Cruise': [
    { name: 'Royal Caribbean', city: 'Cruise Ship' },
    { name: 'Carnival Cruise Line', city: 'Cruise Ship' },
    { name: 'Norwegian Cruise Line', city: 'Cruise Ship' },
    { name: 'MSC Cruises', city: 'Cruise Ship' },
    { name: 'Princess Cruises', city: 'Cruise Ship' },
    { name: 'Celebrity Cruises', city: 'Cruise Ship' },
    { name: 'Disney Cruise Line', city: 'Cruise Ship' },
    { name: 'Holland America Line', city: 'Cruise Ship' },
    { name: 'Viking Ocean Cruises', city: 'Cruise Ship' },
  ],
};

export const US_STATES = Object.keys(CASINOS_BY_STATE).sort();
